#!/bin/sh

repo_name=$1

echo $repo_name

curl -u 'masonhorder' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\", \"private\":\"true\" }"

mkdir ~/Documents/Projects/$repo_name

cd ~/Documents/Projects/$repo_name

echo "# $repo_name" >> README.md

git init .

git add .

git commit -a -m "first commit"

git remote add origin https://github.com/masonhorder/$repo_name.git

git push -u origin master

atom .
